name: Build ShadowsocksR (.NET Framework 4.8)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: shadowsocks-csharp.sln
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # .NET Framework 不用 setup-dotnet（可删）

    # 必须：MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 还原 NuGet
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # 编译（关键）
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration

    # 上传 exe（直接输出 bin）
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shadowsocksr-net48
        path: |
          **/bin/${{ env.Configuration }}/**
