name: Build ShadowsocksR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: shadowsocks-csharp.sln
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name -c $env:Configuration --no-restore

    - name: Publish
      run: dotnet publish $env:Solution_Name -c $env:Configuration -r win-x64 --self-contained true --no-build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shadowsocksr
        path: |
          **/publish/**
